# Generated by Django 5.2.6 on 2025-09-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        
        migrations.RunSQL("""
        INSERT INTO shop_collection (title) VALUES ('collection1');
        """, """
        DELETE FROM shop_collection WHERE title = 'collection1';
        """)
    ]